### ISSUE TITLE
Test Failure on macOS Sierra

### ISSUE THREAD

**Issue by genio** [mbeijen/File-MimeInfo#26] opened 2017-01-10 19:56 UTC
This is perl 5, version 24, subversion 0 (v5.24.0) built for darwin-2level
(with 1 registered patch, see perl -V for more detail)

Here are the results of ```cpanm File::MimeInfo```

```
cpanm (App::cpanminus) 1.7042 on perl 5.024000 built for darwin-2level
Work directory is /Users/cwhitener/.cpanm/work/1484078023.15266
You have make /usr/bin/make
You have LWP 6.15
You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
You have /usr/bin/unzip
Searching File::MimeInfo () on cpanmetadb ...
--> Working on File::MimeInfo
Fetching http://www.cpan.org/authors/id/M/MI/MICHIELB/File-MimeInfo-0.28.tar.gz
-> OK
Unpacking File-MimeInfo-0.28.tar.gz
Entering File-MimeInfo-0.28
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.24)
Configuring File-MimeInfo-0.28
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for File::MimeInfo
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Pod::Usage 0 ... Yes (1.69)
Checking if you have Fcntl 0 ... Yes (1.13)
Checking if you have Carp 0 ... Yes (1.40)
Checking if you have File::DesktopEntry 0.04 ... Yes (0.22)
Checking if you have Exporter 0 ... Yes (5.72)
Checking if you have File::BaseDir 0.03 ... Yes (0.07)
Building and testing File-MimeInfo-0.28
cp lib/File/MimeInfo/Rox.pm blib/lib/File/MimeInfo/Rox.pm
cp lib/File/MimeInfo.pm blib/lib/File/MimeInfo.pm
cp lib/File/MimeInfo/Magic.pm blib/lib/File/MimeInfo/Magic.pm
cp lib/File/MimeInfo/Applications.pm blib/lib/File/MimeInfo/Applications.pm
cp lib/File/MimeInfo/Cookbook.pod blib/lib/File/MimeInfo/Cookbook.pod
cp mimeopen blib/script/mimeopen
"/Users/cwhitener/perl5/perlbrew/perls/perl-5.24.0/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/mimeopen
cp mimetype blib/script/mimetype
"/Users/cwhitener/perl5/perlbrew/perls/perl-5.24.0/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/mimetype
Manifying 2 pod documents
Manifying 5 pod documents
PERL_DL_NONLAZY=1 "/Users/cwhitener/perl5/perlbrew/perls/perl-5.24.0/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
WARNING: You don't seem to have any mimeinfo.cache files.
Try running the update-desktop-database command. If you
don't have this command you should install the
desktop-file-utils package. This package is available from
http://freedesktop.org/wiki/Software/desktop-file-utils/
t/00_use_ok.t ...... ok
t/01_normal.t ...... ok
t/02_magic.t ....... ok
t/03_rox.t ......... ok
t/04_IO_objects.t .. ok
t/05_more.t ........ ok
t/06_pod_ok.t ...... ok
WARNING: You don't seem to have any mimeinfo.cache files.
Try running the update-desktop-database command. If you
don't have this command you should install the
desktop-file-utils package. This package is available from
http://freedesktop.org/wiki/Software/desktop-file-utils/
t/07_pod_cover.t ... ok
t/08_changes.t ..... ok
t/09_no404s.t ...... skipped: Skip $ENV{EXTENDED_TESTING} is not set
WARNING: You don't seem to have a mime-info database. The
shared-mime-info package is available from http://freedesktop.org/ .
Can't locate object method "seek" via package "Path::Tiny" at /Users/cwhitener/.cpanm/work/1484078023.15266/File-MimeInfo-0.28/blib/lib/File/MimeInfo.pm line 115.
t/10filehandle.t ...
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run

Test Summary Report
-------------------
t/10filehandle.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=11, Tests=89,  1 wallclock secs ( 0.04 usr  0.02 sys +  0.63 cusr  0.09 csys =  0.78 CPU)
Result: FAIL
Failed 1/11 test programs. 0/89 subtests failed.
make: *** [test_dynamic] Error 2
-> FAIL Installing File::MimeInfo failed. See /Users/cwhitener/.cpanm/work/1484078023.15266/build.log for details. Retry with --force to force install it.
```

**Comment by mbeijen** [comment] 2017-01-10 20:41
Thanks for raising this issue.

The problem is actually in this: `WARNING: You don't seem to have a mime-info database`. The message about `seek` is fixed in 3a6fa004cadb7ffc0eff76a40b7a1e4ae73dc4e8 but the test fails if you don't have the mime-info database available, which is the case on Windows or OS X by default.

I was thinking about maybe starting to ship our own version of mime-info as a fall back in case the system does not have this available. On the other hand this would mean a dependency on `File::Share` and I want `File::MimeInfo` to be light on dependencies as it is installed for instance on Debian systems by the 'default' installation.

Do you have any opinion on this?

**Comment by genio** [comment] 2017-01-10 20:51
Gah. You're right.

With homebrew, ```brew install desktop-file-utils``` resolved the issue.  I don't know that shipping your own is the best option, but I also haven't yet tried to see how complicated getting desktop-file-utils on Windows is.

In other words, I should have heeded the warnings and read the docs before assuming that those were OK to overlook because there was an error that was an easy scapegoat.

Thanks!

**Closed** 2017-01-19 18:46 UTC

**Comment by eserte** [comment] 2018-03-25 21:42
> Do you have any opinion on this?

The mime-info database could go into a second CPAN distribution (e.g. an Alien::*-like distribution, or a distribution just containing and installing the mime-info file(s)).

The Makefile.PL in File-MimeInfo would then check if a native mime-info is available, and otherwise inject a dependency into PREREQ_PM.

**Comment by cub-uanic** [comment] 2019-10-28 02:38
> With homebrew, `brew install desktop-file-utils` resolved the issue.

For me, that was not enough, I was nee to run `brew install desktop-file-utils shared-mime-info`.
Hope this will be useful for other Mac users.
